### ISSUE TITLE
Uptime() is deprecated as of OSX 10.8

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/tcpreplay#3]
Timer code needs to adapt

**Comment by synfinatic** [comment]
As is AbsoluteToNanoseconds() and SubAbsoluteFromAbsolute()

**Comment by synfinatic** [comment]
more info here:

http://stackoverflow.com/questions/1450737/what-is-mach-absolute-time-based-on-on-iphone/4753909#4753909

and 

http://stackoverflow.com/questions/16049181/what-to-do-about-carbon-functions-that-are-deprecated-in-macos-x-10-8-x

**Comment by fklassen** [comment]
Fixed here https://github.com/appneta/tcpreplay/commit/9c3666c05fa21cf8bbd2e4dc5c9a4655284dc234
